blank_issues_enabled: false
contact_links:
  - name: Search Issues
    url: https://github.com/joygqz/fluxforge/issues?q=is%3Aissue
    about: Search existing issues before creating a new one
  - name: Documentation
    url: https://github.com/joygqz/fluxforge#readme
    about: Read the full documentation and examples
